<?php

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pages')->insert([
            [
                'title'         => 'Dažniausiai užduodami klausimai',
                'slug'          => 'duk',
                'content'       => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minus inventore ea, perferendis nam corrupti, explicabo eveniet eius impedit ab esse expedita alias cum laborum, ducimus illo molestiae atque nihil, itaque sunt ipsam. Deleniti exercitationem odit quidem fuga illum laborum accusantium corporis pariatur voluptate debitis voluptas possimus quibusdam, distinctio veritatis hic odio ipsa doloremque autem est ad itaque, dicta consectetur enim adipisci totam. Dolorum iste laudantium nihil perspiciatis eius velit iure, suscipit atque excepturi aliquam autem, reiciendis eos labore tempora eaque adipisci beatae unde magni ipsum incidunt ex veniam, dignissimos hic praesentium doloremque. Illo quia excepturi quisquam repellat, repellendus possimus?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia doloremque dolores tempora odio modi possimus velit dolor, esse adipisci! Quam aliquam incidunt tempore, odio voluptatem rerum amet facilis accusamus atque non deleniti labore esse! Repellat a tempora dicta, neque, fugiat, sed tempore temporibus explicabo eaque expedita consequuntur et itaque optio aperiam corporis cupiditate! Veritatis quia quas ipsum accusamus excepturi, minima laborum ut perferendis, atque vitae, earum id repellendus veniam beatae dolorum suscipit debitis. Consequatur rerum facilis iusto. Accusamus rerum similique omnis cumque odio, at veritatis commodi atque rem consequatur, culpa nemo, minus saepe unde fugit inventore in eos architecto. Quae consequatur asperiores, nihil illum minus necessitatibus autem non ipsum, excepturi tempora odit praesentium quasi velit harum. Quibusdam accusamus, temporibus quia nemo eligendi sed voluptatum aliquam cumque iure asperiores harum ea corporis, numquam, at dolores quos minus debitis dolor quas eum, sunt doloribus inventore. Facilis, mollitia, facere! Aut praesentium, vitae odit eum fugit repudiandae consectetur. Voluptas animi eligendi quo quis quisquam provident vel, iusto, repudiandae optio, hic nam placeat quae, error doloremque in perferendis exercitationem rem! Voluptates optio rerum rem est eligendi facilis voluptatem dolorum in suscipit aut dolor culpa, laborum deserunt quis eveniet ipsam, accusantium blanditiis. Veritatis beatae corrupti ipsum minus numquam soluta, harum voluptas consequuntur quo sunt molestiae iure deleniti omnis sed cumque. Facere quae, asperiores laboriosam perspiciatis? Error atque repudiandae assumenda, natus in recusandae nostrum quod ducimus ipsa fuga facere voluptatum omnis quia corporis ratione dolorem laboriosam dignissimos. Ipsum accusantium laborum, pariatur autem porro saepe adipisci tempora quidem.</p>',
                'meta_title'    => 'Dažniausiai užduodami klausimai',
                'status'        => 1
            ], [
                'title'         => 'Kontaktai',
                'slug'          => 'kontaktai',
                'content'       => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minus inventore ea, perferendis nam corrupti, explicabo eveniet eius impedit ab esse expedita alias cum laborum, ducimus illo molestiae atque nihil, itaque sunt ipsam. Deleniti exercitationem odit quidem fuga illum laborum accusantium corporis pariatur voluptate debitis voluptas possimus quibusdam, distinctio veritatis hic odio ipsa doloremque autem est ad itaque, dicta consectetur enim adipisci totam. Dolorum iste laudantium nihil perspiciatis eius velit iure, suscipit atque excepturi aliquam autem, reiciendis eos labore tempora eaque adipisci beatae unde magni ipsum incidunt ex veniam, dignissimos hic praesentium doloremque. Illo quia excepturi quisquam repellat, repellendus possimus?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia doloremque dolores tempora odio modi possimus velit dolor, esse adipisci! Quam aliquam incidunt tempore, odio voluptatem rerum amet facilis accusamus atque non deleniti labore esse! Repellat a tempora dicta, neque, fugiat, sed tempore temporibus explicabo eaque expedita consequuntur et itaque optio aperiam corporis cupiditate! Veritatis quia quas ipsum accusamus excepturi, minima laborum ut perferendis, atque vitae, earum id repellendus veniam beatae dolorum suscipit debitis. Consequatur rerum facilis iusto. Accusamus rerum similique omnis cumque odio, at veritatis commodi atque rem consequatur, culpa nemo, minus saepe unde fugit inventore in eos architecto. Quae consequatur asperiores, nihil illum minus necessitatibus autem non ipsum, excepturi tempora odit praesentium quasi velit harum. Quibusdam accusamus, temporibus quia nemo eligendi sed voluptatum aliquam cumque iure asperiores harum ea corporis, numquam, at dolores quos minus debitis dolor quas eum, sunt doloribus inventore. Facilis, mollitia, facere! Aut praesentium, vitae odit eum fugit repudiandae consectetur. Voluptas animi eligendi quo quis quisquam provident vel, iusto, repudiandae optio, hic nam placeat quae, error doloremque in perferendis exercitationem rem! Voluptates optio rerum rem est eligendi facilis voluptatem dolorum in suscipit aut dolor culpa, laborum deserunt quis eveniet ipsam, accusantium blanditiis. Veritatis beatae corrupti ipsum minus numquam soluta, harum voluptas consequuntur quo sunt molestiae iure deleniti omnis sed cumque. Facere quae, asperiores laboriosam perspiciatis? Error atque repudiandae assumenda, natus in recusandae nostrum quod ducimus ipsa fuga facere voluptatum omnis quia corporis ratione dolorem laboriosam dignissimos. Ipsum accusantium laborum, pariatur autem porro saepe adipisci tempora quidem.</p>',
                'meta_title'    => 'Kontaktai',
                'status'        => 1
            ], [
                'title'         => 'Naudojimosi taisyklės',
                'slug'          => 'naudojimosi-taisykles',
                'content'       => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam minus inventore ea, perferendis nam corrupti, explicabo eveniet eius impedit ab esse expedita alias cum laborum, ducimus illo molestiae atque nihil, itaque sunt ipsam. Deleniti exercitationem odit quidem fuga illum laborum accusantium corporis pariatur voluptate debitis voluptas possimus quibusdam, distinctio veritatis hic odio ipsa doloremque autem est ad itaque, dicta consectetur enim adipisci totam. Dolorum iste laudantium nihil perspiciatis eius velit iure, suscipit atque excepturi aliquam autem, reiciendis eos labore tempora eaque adipisci beatae unde magni ipsum incidunt ex veniam, dignissimos hic praesentium doloremque. Illo quia excepturi quisquam repellat, repellendus possimus?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia doloremque dolores tempora odio modi possimus velit dolor, esse adipisci! Quam aliquam incidunt tempore, odio voluptatem rerum amet facilis accusamus atque non deleniti labore esse! Repellat a tempora dicta, neque, fugiat, sed tempore temporibus explicabo eaque expedita consequuntur et itaque optio aperiam corporis cupiditate! Veritatis quia quas ipsum accusamus excepturi, minima laborum ut perferendis, atque vitae, earum id repellendus veniam beatae dolorum suscipit debitis. Consequatur rerum facilis iusto. Accusamus rerum similique omnis cumque odio, at veritatis commodi atque rem consequatur, culpa nemo, minus saepe unde fugit inventore in eos architecto. Quae consequatur asperiores, nihil illum minus necessitatibus autem non ipsum, excepturi tempora odit praesentium quasi velit harum. Quibusdam accusamus, temporibus quia nemo eligendi sed voluptatum aliquam cumque iure asperiores harum ea corporis, numquam, at dolores quos minus debitis dolor quas eum, sunt doloribus inventore. Facilis, mollitia, facere! Aut praesentium, vitae odit eum fugit repudiandae consectetur. Voluptas animi eligendi quo quis quisquam provident vel, iusto, repudiandae optio, hic nam placeat quae, error doloremque in perferendis exercitationem rem! Voluptates optio rerum rem est eligendi facilis voluptatem dolorum in suscipit aut dolor culpa, laborum deserunt quis eveniet ipsam, accusantium blanditiis. Veritatis beatae corrupti ipsum minus numquam soluta, harum voluptas consequuntur quo sunt molestiae iure deleniti omnis sed cumque. Facere quae, asperiores laboriosam perspiciatis? Error atque repudiandae assumenda, natus in recusandae nostrum quod ducimus ipsa fuga facere voluptatum omnis quia corporis ratione dolorem laboriosam dignissimos. Ipsum accusantium laborum, pariatur autem porro saepe adipisci tempora quidem.</p>',
                'meta_title'    => 'Naudojimosi taisyklės',
                'status'        => 1
            ]
        ]);
    }
}
